language: python
sudo: false
python:
  - "nightly"
  - "3.6"
  - "3.5"
  - "3.4"
install:
  - pip install -r test-requirements.txt .
script:
  - |
    if [[ "$TEST_LINT" = 1 ]]; then
      flake8 oauthenticator
    else
      py.test --cov oauthenticator oauthenticator
    fi
matrix:
  include:
    python: "3.5"
    env: TEST_LINT=1
